### PR TITLE
Public Domain Uppercase

### PR DESCRIPTION
**Pull request by maennchen**
This removes a few false positives.

### CODE REVIEW

**Comment by eladnava** [comment]
Hi @maennchen,
Thanks so much for this PR! Can you please explain the reason behind these changes? Is there any package you are aware of whose license returned by `tldrlegal` is not using the same casing as defined in this project?

I would like to understand the issue first before merging this.

Thanks! 👍

**Comment by eladnava** [comment]
Hi @maennchen,
Thanks so much for this PR! Can you please explain the reason behind these changes? Is there any package you are aware of whose license is not being parsed correctly by this library due to casing?

I would like to understand the issue first before merging this.

Thanks! 👍

**Comment by maennchen** [comment]
Sure, there are for example many packages like `jsonify`, that specify `Public Domain` as the license. The code of this tool specifies `Public domain`.

**Comment by eladnava** [comment]
I think that the real issue is that `legally`, the library we use to determine npm packages' licenses, returns the "Public Domain" license as `Public Domain` while we reference it as `Public domain` in the `licenseObligations.js` file of this project, causing detection to fail.

I ran the following to check this:
```
npm install -g legally
legally jsonify
```

So the solution would simply be to modify `licenseObligations.js` and capitalize `domain` in `Public domain`. Unless you can provide an other example of a package returning a different license casing.

**Comment by maennchen** [comment]
`legally` is also not normalising the names. It gives a different output for upper & lowercase.

**Comment by eladnava** [comment]
Hi @maennchen,
Great observation -- can you please provide two npm packages with the same license being returned in different casing?

**Comment by maennchen** [comment]
Yes quite a few.

I think the most you can see with the BSD 3 Clause License:
https://github.com/search?l=&q=license+%22BSD-2-Clause%22+language%3AJSON+language%3AJavaScript&ref=advsearch&type=Code&utf8=%E2%9C%93

**Comment by eladnava** [comment]
That search returns a lot of "License.json" files which are not related to the `npm` package ecosystem.

npm packages specifying their license within `package.json` must use the SPDX license identifier which is case-sensitive:
https://spdx.org/licenses/

Here is that same search without "License.json" files:
https://github.com/search?p=2&q=license+%22BSD-2-Clause%22+language%3AJSON+language%3AJavaScript+-License.json&type=Code&utf8=%E2%9C%93

npm will not accept an SPDX license name in the wrong case.

**Comment by maennchen** [comment]
Ok, I changed the PR to just write Public Domain Uppercase.

**Comment by eladnava** [comment]
Excellent, thanks so much for your help! 👍

**Comment by eladnava** [comment]
Merged and published v1.0.5 to npm.

**Pull request merged**
