### PR TITLE
Add The Unlicense

### PR DESCRIPTION
**Pull request by maennchen**
~~Depends on #4~~

### CODE REVIEW

**Comment by eladnava** [comment]
Excellent, thanks for the updates @maennchen!

**Comment by eladnava** [comment]
Merged and published v1.0.5 to npm. 👍

**Comment by maennchen** [comment]
@eladnava Do you plan to just support the newest versions of licences or would you also accept older ones like AFL 2.1?

**Comment by eladnava** [comment]
@maennchen All licenses are welcome, mate! Especially since I have encountered a few packages using this license. I wanted to specify `AFL-2.1` but `tldrlegal.com` does not have any information about it:
https://tldrlegal.com/license/academic-free-license-v.-2.1

**Comment by maennchen** [comment]
@eladnava I suggested a change on tldrlegal. I will make a PR if they accept it.

**Comment by eladnava** [comment]
@maennchen Awesome mate!

**Pull request merged**
