### PR TITLE
Add compatibility check.

### PR DESCRIPTION
**Pull request by phillbaker**
Similar to https://github.com/librariesio/license-compatibility and https://github.com/HansHammel/license-compatibility-checker.

As [wikipedia explains](https://en.wikipedia.org/wiki/License_compatibility):

> different licenses can contain contradictory requirements, rendering it impossible to legally combine source code from separately-licensed software in order to create and publish a new program

This extension adds a check to ensure that the most restrictive license does not conflict with the least restrictive. Example (based on changing the license in legally locally in node_modules):

screen shot 2018-03-18 at 11 13 28 am

This could also be expressed using SPDX, however, that would probably add an additional layer of complexity.

### CODE REVIEW

**Comment by eladnava** [comment]
Hi @phillbaker,
Nice to meet you, thanks for your PR!

Can you please provide a concrete example of two licenses that contradict each other and are therefore incompatible? And what is the exact wording or requirement stated in both of these licenses that contradicts each other?

**Comment by phillbaker** [comment]
HI @eladnava thanks for getting back, I should have mentioned, this is a follow up to my earlier PR: https://github.com/eladnava/tldrlegal/pull/7. 

I'm not a lawyer, so it's hard for me to point to specific terms in the licenses, but we're primarily interested in two types of incompatibilities:
* a library is licensed so that it does not allow use by the organization using it (common examples would be software that requires a commercial license, e.g. [highcharts](https://github.com/highcharts/highcharts/blob/master/license.txt) or [the JSON license](https://lwn.net/Articles/707510/))
* a library is licensed under a "network copyleft" license such as [any version of the AGPL](https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License) which forces disclosure of source code for any "derived" or "combined" software using the library. Examples of NPM libraries licensed this way include: https://www.npmjs.com/package/jbus-common-util, https://www.npmjs.com/package/@verady/veranet, https://www.npmjs.com/package/hatchjs.

The second example it seems like would be covered under the obligations to disclosure source however.

**Comment by eladnava** [comment]
@phillbaker After reading up on the `JSON` license it appears this is just the same as the MIT license but with an additional line `Software shall be used for Good, not Evil`. Where does it mention a commercial use requirement?

And in the case of `highcharts`, their npm module and GitHub repo don't actually reference any well-known SPDX license, so `tldrlegal` can't help you with that module's license requirements anyway. Upon examining their license page, they do have a non-commercial license (`CreativeCommons Attribution-NonCommercial`):
https://shop.highsoft.com/highcharts

Could you please provide other examples that this PR addresses?

**Comment by phillbaker** [comment]
Hi @eladnava, thanks for the reply.

We've now come to the understanding that "compatibility" is the higher level concept of whether any obligations have not been met. So the current approach already answers the question of compatibility. I'll close this PR as redundant.

A couple of issues coming out of this PR - how would you feel about adding to the existing license list?

**Comment by eladnava** [comment]
Hi @phillbaker,
Absolutely, adding information about additional licenses and their obligations to this module would be a great idea. Which missing licenses are you referring to? "JSON" and "CreativeCommons Attribution-NonCommercial"?

Would you like to submit a PR to support these licenses?

**Comment by phillbaker** [comment]
@eladnava there are quite a few licenses listed in https://github.com/eladnava/tldrlegal/pull/8/files#diff-69011afb39484136771495cf8d3e806c, some of the more frequently used ones: LGPL, AGPL, Eclipse (EPL), mozilla (MPL), as well as versions/variants of the currently listed licenses.

**Comment by eladnava** [comment]
@phillbaker Awesome, would you be interested in submitting a PR to add support to some of these licenses based on https://tldrlegal.com?

**Pull request closed without merging**
